/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandingConfig {
  'theme' : [] | [string],
  'primaryColor' : [] | [string],
  'logo' : [] | [ExternalBlob],
  'siteName' : string,
  'favicon' : [] | [ExternalBlob],
  'secondaryColor' : [] | [string],
}
export interface CartItem { 'quantity' : bigint, 'product' : Product }
export type ExternalBlob = Uint8Array;
export interface HomepageConfig {
  'heroImage' : [] | [ExternalBlob],
  'promotionalText' : string,
  'heroMotto' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'stripeProductId' : string,
  'shape' : string,
  'viewCount' : bigint,
  'stripeProductDescription' : string,
  'inventoryCount' : bigint,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ShopDetails {
  'address' : {
    'street' : string,
    'country' : string,
    'city' : string,
    'zipcode' : string,
  },
  'openingHours' : {
    'tuesday' : [] | [string],
    'wednesday' : [] | [string],
    'saturday' : [] | [string],
    'thursday' : [] | [string],
    'sunday' : [] | [string],
    'friday' : [] | [string],
    'monday' : [] | [string],
  },
  'shopName' : string,
  'companyDetails' : { 'taxId' : string, 'vatId' : string },
  'contactDetails' : { 'email' : string, 'phone' : string },
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SortingOrder = { 'bestSelling' : null } |
  { 'newest' : null } |
  { 'mostViewed' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'stripeAccountId' : [] | [string],
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'addOrUpdateProductImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, string, string, Array<ExternalBlob>, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkoutCartItems' : ActorMethod<[string, string], [] | [string]>,
  'clearAllCarts' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createNoShippingCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'emptyCart' : ActorMethod<[], undefined>,
  'getBestSellingProducts' : ActorMethod<[], Array<Product>>,
  'getBrandingConfig' : ActorMethod<[], BrandingConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCartTotal' : ActorMethod<[], bigint>,
  'getHomepageConfig' : ActorMethod<[], HomepageConfig>,
  'getMostViewedProducts' : ActorMethod<[], Array<Product>>,
  'getNewestProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductCount' : ActorMethod<[], bigint>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsBySorting' : ActorMethod<[SortingOrder], Array<Product>>,
  'getShopDetails' : ActorMethod<[], [] | [ShopDetails]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalInventoryValue' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeAllCartItems' : ActorMethod<[], undefined>,
  'removeCartItem' : ActorMethod<[bigint], undefined>,
  'replaceProductImage' : ActorMethod<
    [bigint, bigint, ExternalBlob],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'trackProductView' : ActorMethod<[bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBrandingConfig' : ActorMethod<[BrandingConfig], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateHomepageConfig' : ActorMethod<[HomepageConfig], undefined>,
  'updateInventoryCount' : ActorMethod<[bigint, bigint], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
      [] | [Array<ExternalBlob>],
      [] | [bigint],
    ],
    undefined
  >,
  'updateShopDetails' : ActorMethod<[ShopDetails], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];