/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BonusItemConfig {
  'url' : string,
  'title' : string,
  'description' : string,
  'enabled' : boolean,
}
export interface BrandingConfig {
  'theme' : [] | [string],
  'primaryColor' : [] | [string],
  'logo' : [] | [ExternalBlob],
  'siteName' : string,
  'favicon' : [] | [ExternalBlob],
  'secondaryColor' : [] | [string],
}
export interface CartItem { 'quantity' : bigint, 'product' : Product }
export interface DescriptionTemplate {
  'id' : bigint,
  'content' : string,
  'name' : string,
  'createdAt' : Time,
}
export interface DiscountCode {
  'id' : string,
  'active' : boolean,
  'value' : number,
  'code' : string,
  'createdAt' : bigint,
  'discountType' : { 'percentage' : null } |
    { 'fixedAmount' : null },
}
export type ExternalBlob = Uint8Array;
export interface HomepageConfig {
  'heroImage' : [] | [ExternalBlob],
  'promotionalText' : string,
  'heroMotto' : string,
}
export interface OcarinaFingeringMap {
  'note0' : Array<boolean>,
  'note1' : Array<boolean>,
  'note2' : Array<boolean>,
  'note3' : Array<boolean>,
  'note4' : Array<boolean>,
  'note5' : Array<boolean>,
  'note6' : Array<boolean>,
  'note7' : Array<boolean>,
}
export type OcarinaNoteDegrees = Array<bigint>;
export interface OcarinaProfile {
  'id' : bigint,
  'scaleName' : string,
  'fingeringMap' : OcarinaFingeringMap,
  'iconMappings' : [] | [Array<string>],
  'noteDegreeMappings' : OcarinaNoteDegrees,
  'noteAudioBlobs' : [] | [Array<ExternalBlob>],
}
export interface PaymentSettings {
  'bonusItemConfig' : BonusItemConfig,
  'proOcarinaAppUrl' : string,
}
export interface Product {
  'id' : bigint,
  'displayOrder' : bigint,
  'name' : string,
  'createdAt' : Time,
  'stripeProductId' : string,
  'shape' : string,
  'viewCount' : bigint,
  'stripeProductDescription' : string,
  'category' : string,
  'inventoryCount' : bigint,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ShopDetails {
  'address' : {
    'street' : string,
    'country' : string,
    'city' : string,
    'zipcode' : string,
  },
  'openingHours' : {
    'tuesday' : [] | [string],
    'wednesday' : [] | [string],
    'saturday' : [] | [string],
    'thursday' : [] | [string],
    'sunday' : [] | [string],
    'friday' : [] | [string],
    'monday' : [] | [string],
  },
  'shopName' : string,
  'companyDetails' : { 'taxId' : string, 'vatId' : string },
  'contactDetails' : { 'email' : string, 'phone' : string },
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SortingOrder = { 'bestSelling' : null } |
  { 'newest' : null } |
  { 'mostViewed' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'stripeAccountId' : [] | [string],
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'addOrUpdateProductImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      Array<ExternalBlob>,
      bigint,
      string,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkoutCartItems' : ActorMethod<[string, string], [] | [string]>,
  'clearAllCarts' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDescriptionTemplate' : ActorMethod<[string, string], bigint>,
  'createDiscountCode' : ActorMethod<
    [
      string,
      string,
      { 'percentage' : null } |
        { 'fixedAmount' : null },
      number,
    ],
    undefined
  >,
  'createNoShippingCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteDescriptionTemplate' : ActorMethod<[bigint], undefined>,
  'deleteDiscountCode' : ActorMethod<[string], undefined>,
  'deleteOcarinaProfile' : ActorMethod<[bigint], undefined>,
  'deleteStripeConfig' : ActorMethod<[], undefined>,
  'emptyCart' : ActorMethod<[], undefined>,
  'getBestSellingProducts' : ActorMethod<[], Array<Product>>,
  'getBonusItemConfig' : ActorMethod<[], BonusItemConfig>,
  'getBrandingConfig' : ActorMethod<[], BrandingConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCartTotal' : ActorMethod<[], bigint>,
  'getDescriptionTemplates' : ActorMethod<[], Array<DescriptionTemplate>>,
  'getDiscountCodes' : ActorMethod<[], Array<DiscountCode>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getFingeringMap' : ActorMethod<[bigint], OcarinaFingeringMap>,
  'getHomepageConfig' : ActorMethod<[], HomepageConfig>,
  'getMostViewedProducts' : ActorMethod<[], Array<Product>>,
  'getNewestProducts' : ActorMethod<[], Array<Product>>,
  'getNoteAudio' : ActorMethod<[bigint, bigint], ExternalBlob>,
  'getNoteIcon' : ActorMethod<[bigint, bigint], string>,
  'getOcarinaProfile' : ActorMethod<[bigint], [] | [OcarinaProfile]>,
  'getOcarinaProfiles' : ActorMethod<[], Array<OcarinaProfile>>,
  'getPaymentSettings' : ActorMethod<[], PaymentSettings>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductCount' : ActorMethod<[], bigint>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsBySorting' : ActorMethod<[SortingOrder], Array<Product>>,
  'getShopDetails' : ActorMethod<[], [] | [ShopDetails]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalInventoryValue' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeAllCartItems' : ActorMethod<[], undefined>,
  'removeCartItem' : ActorMethod<[bigint], undefined>,
  'replaceProductImage' : ActorMethod<
    [bigint, bigint, ExternalBlob],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveNoteAudio' : ActorMethod<[bigint, bigint, ExternalBlob], undefined>,
  'saveNoteIcon' : ActorMethod<[bigint, bigint, string], undefined>,
  'saveOcarinaProfile' : ActorMethod<[OcarinaProfile], undefined>,
  'scanSheetMusic' : ActorMethod<[string], Array<bigint>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'trackProductView' : ActorMethod<[bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBonusItemConfig' : ActorMethod<[BonusItemConfig], undefined>,
  'updateBrandingConfig' : ActorMethod<[BrandingConfig], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateDescriptionTemplate' : ActorMethod<
    [bigint, string, string],
    undefined
  >,
  'updateDiscountCode' : ActorMethod<
    [
      string,
      string,
      { 'percentage' : null } |
        { 'fixedAmount' : null },
      number,
      boolean,
    ],
    undefined
  >,
  'updateHomepageConfig' : ActorMethod<[HomepageConfig], undefined>,
  'updateInventoryCount' : ActorMethod<[bigint, bigint], undefined>,
  'updatePaymentSettings' : ActorMethod<[string, BonusItemConfig], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
      [] | [Array<ExternalBlob>],
      [] | [bigint],
      [] | [string],
    ],
    undefined
  >,
  'updateProductDisplayOrder' : ActorMethod<[Array<bigint>], undefined>,
  'updateShopDetails' : ActorMethod<[ShopDetails], undefined>,
  'validateDiscountCode' : ActorMethod<[string], [] | [DiscountCode]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];