/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'stripeProductId' : IDL.Text,
  'shape' : IDL.Text,
  'viewCount' : IDL.Nat,
  'stripeProductDescription' : IDL.Text,
  'category' : IDL.Text,
  'inventoryCount' : IDL.Nat,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const BrandingConfig = IDL.Record({
  'theme' : IDL.Opt(IDL.Text),
  'primaryColor' : IDL.Opt(IDL.Text),
  'logo' : IDL.Opt(ExternalBlob),
  'siteName' : IDL.Text,
  'favicon' : IDL.Opt(ExternalBlob),
  'secondaryColor' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'stripeAccountId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const DescriptionTemplate = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const HomepageConfig = IDL.Record({
  'heroImage' : IDL.Opt(ExternalBlob),
  'promotionalText' : IDL.Text,
  'heroMotto' : IDL.Text,
});
export const SortingOrder = IDL.Variant({
  'bestSelling' : IDL.Null,
  'newest' : IDL.Null,
  'mostViewed' : IDL.Null,
});
export const ShopDetails = IDL.Record({
  'address' : IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'zipcode' : IDL.Text,
  }),
  'openingHours' : IDL.Record({
    'tuesday' : IDL.Opt(IDL.Text),
    'wednesday' : IDL.Opt(IDL.Text),
    'saturday' : IDL.Opt(IDL.Text),
    'thursday' : IDL.Opt(IDL.Text),
    'sunday' : IDL.Opt(IDL.Text),
    'friday' : IDL.Opt(IDL.Text),
    'monday' : IDL.Opt(IDL.Text),
  }),
  'shopName' : IDL.Text,
  'companyDetails' : IDL.Record({ 'taxId' : IDL.Text, 'vatId' : IDL.Text }),
  'contactDetails' : IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text }),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addOrUpdateProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkoutCartItems' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'clearAllCarts' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDescriptionTemplate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createNoShippingCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteDescriptionTemplate' : IDL.Func([IDL.Nat], [], []),
  'deleteStripeConfig' : IDL.Func([], [], []),
  'emptyCart' : IDL.Func([], [], []),
  'getBestSellingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBrandingConfig' : IDL.Func([], [BrandingConfig], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getDescriptionTemplates' : IDL.Func(
      [],
      [IDL.Vec(DescriptionTemplate)],
      ['query'],
    ),
  'getHomepageConfig' : IDL.Func([], [HomepageConfig], ['query']),
  'getMostViewedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getNewestProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsBySorting' : IDL.Func(
      [SortingOrder],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getShopDetails' : IDL.Func([], [IDL.Opt(ShopDetails)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalInventoryValue' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAllCartItems' : IDL.Func([], [], []),
  'removeCartItem' : IDL.Func([IDL.Nat], [], []),
  'replaceProductImage' : IDL.Func([IDL.Nat, IDL.Nat, ExternalBlob], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'trackProductView' : IDL.Func([IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBrandingConfig' : IDL.Func([BrandingConfig], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateDescriptionTemplate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateHomepageConfig' : IDL.Func([HomepageConfig], [], []),
  'updateInventoryCount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(ExternalBlob)),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateShopDetails' : IDL.Func([ShopDetails], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'stripeProductId' : IDL.Text,
    'shape' : IDL.Text,
    'viewCount' : IDL.Nat,
    'stripeProductDescription' : IDL.Text,
    'category' : IDL.Text,
    'inventoryCount' : IDL.Nat,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const BrandingConfig = IDL.Record({
    'theme' : IDL.Opt(IDL.Text),
    'primaryColor' : IDL.Opt(IDL.Text),
    'logo' : IDL.Opt(ExternalBlob),
    'siteName' : IDL.Text,
    'favicon' : IDL.Opt(ExternalBlob),
    'secondaryColor' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'stripeAccountId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const DescriptionTemplate = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const HomepageConfig = IDL.Record({
    'heroImage' : IDL.Opt(ExternalBlob),
    'promotionalText' : IDL.Text,
    'heroMotto' : IDL.Text,
  });
  const SortingOrder = IDL.Variant({
    'bestSelling' : IDL.Null,
    'newest' : IDL.Null,
    'mostViewed' : IDL.Null,
  });
  const ShopDetails = IDL.Record({
    'address' : IDL.Record({
      'street' : IDL.Text,
      'country' : IDL.Text,
      'city' : IDL.Text,
      'zipcode' : IDL.Text,
    }),
    'openingHours' : IDL.Record({
      'tuesday' : IDL.Opt(IDL.Text),
      'wednesday' : IDL.Opt(IDL.Text),
      'saturday' : IDL.Opt(IDL.Text),
      'thursday' : IDL.Opt(IDL.Text),
      'sunday' : IDL.Opt(IDL.Text),
      'friday' : IDL.Opt(IDL.Text),
      'monday' : IDL.Opt(IDL.Text),
    }),
    'shopName' : IDL.Text,
    'companyDetails' : IDL.Record({ 'taxId' : IDL.Text, 'vatId' : IDL.Text }),
    'contactDetails' : IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text }),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addOrUpdateProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkoutCartItems' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'clearAllCarts' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDescriptionTemplate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createNoShippingCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteDescriptionTemplate' : IDL.Func([IDL.Nat], [], []),
    'deleteStripeConfig' : IDL.Func([], [], []),
    'emptyCart' : IDL.Func([], [], []),
    'getBestSellingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBrandingConfig' : IDL.Func([], [BrandingConfig], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getDescriptionTemplates' : IDL.Func(
        [],
        [IDL.Vec(DescriptionTemplate)],
        ['query'],
      ),
    'getHomepageConfig' : IDL.Func([], [HomepageConfig], ['query']),
    'getMostViewedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getNewestProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsBySorting' : IDL.Func(
        [SortingOrder],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getShopDetails' : IDL.Func([], [IDL.Opt(ShopDetails)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalInventoryValue' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAllCartItems' : IDL.Func([], [], []),
    'removeCartItem' : IDL.Func([IDL.Nat], [], []),
    'replaceProductImage' : IDL.Func([IDL.Nat, IDL.Nat, ExternalBlob], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'trackProductView' : IDL.Func([IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBrandingConfig' : IDL.Func([BrandingConfig], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateDescriptionTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateHomepageConfig' : IDL.Func([HomepageConfig], [], []),
    'updateInventoryCount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(ExternalBlob)),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateShopDetails' : IDL.Func([ShopDetails], [], []),
  });
};

export const init = ({ IDL }) => { return []; };