/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: bigint;
    displayOrder: bigint;
    name: string;
    createdAt: Time;
    stripeProductId: string;
    shape: string;
    viewCount: bigint;
    stripeProductDescription: string;
    category: string;
    inventoryCount: bigint;
    price: bigint;
    images: Array<ExternalBlob>;
}
export interface DescriptionTemplate {
    id: bigint;
    content: string;
    name: string;
    createdAt: Time;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OcarinaFingeringMap {
    note0: Array<boolean>;
    note1: Array<boolean>;
    note2: Array<boolean>;
    note3: Array<boolean>;
    note4: Array<boolean>;
    note5: Array<boolean>;
    note6: Array<boolean>;
    note7: Array<boolean>;
}
export interface OcarinaProfile {
    id: bigint;
    scaleName: string;
    fingeringMap: OcarinaFingeringMap;
    iconMappings?: Array<string>;
    noteDegreeMappings: OcarinaNoteDegrees;
    noteAudioBlobs?: Array<ExternalBlob>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DiscountCode {
    id: string;
    active: boolean;
    value: number;
    code: string;
    createdAt: bigint;
    discountType: Variant_percentage_fixedAmount;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface BrandingConfig {
    theme?: string;
    primaryColor?: string;
    logo?: ExternalBlob;
    siteName: string;
    favicon?: ExternalBlob;
    secondaryColor?: string;
}
export interface PaymentSettings {
    bonusItemConfig: BonusItemConfig;
    proOcarinaAppUrl: string;
}
export interface HomepageConfig {
    heroImage?: ExternalBlob;
    promotionalText: string;
    heroMotto: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ShopDetails {
    address: {
        street: string;
        country: string;
        city: string;
        zipcode: string;
    };
    openingHours: {
        tuesday?: string;
        wednesday?: string;
        saturday?: string;
        thursday?: string;
        sunday?: string;
        friday?: string;
        monday?: string;
    };
    shopName: string;
    companyDetails: {
        taxId: string;
        vatId: string;
    };
    contactDetails: {
        email: string;
        phone: string;
    };
}
export interface BonusItemConfig {
    url: string;
    title: string;
    description: string;
    enabled: boolean;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type OcarinaNoteDegrees = Array<bigint>;
export interface CartItem {
    quantity: bigint;
    product: Product;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    stripeAccountId?: string;
    name: string;
    email: string;
}
export enum SortingOrder {
    bestSelling = "bestSelling",
    newest = "newest",
    mostViewed = "mostViewed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_percentage_fixedAmount {
    percentage = "percentage",
    fixedAmount = "fixedAmount"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCartItem(productId: bigint, quantity: bigint): Promise<void>;
    addOrUpdateProductImage(productId: bigint, image: ExternalBlob): Promise<void>;
    addProduct(name: string, shape: string, price: bigint, stripeProductId: string, stripeProductDescription: string, images: Array<ExternalBlob>, inventoryCount: bigint, category: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkoutCartItems(successUrl: string, cancelUrl: string): Promise<string | null>;
    clearAllCarts(): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createDescriptionTemplate(name: string, content: string): Promise<bigint>;
    createDiscountCode(id: string, code: string, discountType: Variant_percentage_fixedAmount, value: number): Promise<void>;
    createNoShippingCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteDescriptionTemplate(id: bigint): Promise<void>;
    deleteDiscountCode(id: string): Promise<void>;
    deleteOcarinaProfile(productId: bigint): Promise<void>;
    deleteStripeConfig(): Promise<void>;
    emptyCart(): Promise<void>;
    getBestSellingProducts(): Promise<Array<Product>>;
    getBonusItemConfig(): Promise<BonusItemConfig>;
    getBrandingConfig(): Promise<BrandingConfig>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Array<CartItem>>;
    getCartTotal(): Promise<bigint>;
    getDescriptionTemplates(): Promise<Array<DescriptionTemplate>>;
    getDiscountCodes(): Promise<Array<DiscountCode>>;
    getFeaturedProducts(): Promise<Array<Product>>;
    getFingeringMap(productId: bigint): Promise<OcarinaFingeringMap>;
    getHomepageConfig(): Promise<HomepageConfig>;
    getMostViewedProducts(): Promise<Array<Product>>;
    getNewestProducts(): Promise<Array<Product>>;
    getNoteAudio(productId: bigint, noteIndex: bigint): Promise<ExternalBlob>;
    getNoteIcon(productId: bigint, noteIndex: bigint): Promise<string>;
    getOcarinaProfile(productId: bigint): Promise<OcarinaProfile | null>;
    getOcarinaProfiles(): Promise<Array<OcarinaProfile>>;
    getPaymentSettings(): Promise<PaymentSettings>;
    getProduct(productId: bigint): Promise<Product | null>;
    getProductCount(): Promise<bigint>;
    getProducts(): Promise<Array<Product>>;
    getProductsBySorting(sortType: SortingOrder): Promise<Array<Product>>;
    getShopDetails(): Promise<ShopDetails | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTotalInventoryValue(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    removeAllCartItems(): Promise<void>;
    removeCartItem(productId: bigint): Promise<void>;
    replaceProductImage(productId: bigint, imageIndex: bigint, newImage: ExternalBlob): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveNoteAudio(productId: bigint, noteIndex: bigint, audioBlob: ExternalBlob): Promise<void>;
    saveNoteIcon(productId: bigint, noteIndex: bigint, iconId: string): Promise<void>;
    saveOcarinaProfile(profile: OcarinaProfile): Promise<void>;
    scanSheetMusic(url: string): Promise<Array<bigint>>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    trackProductView(productId: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBonusItemConfig(bonusItemConfig: BonusItemConfig): Promise<void>;
    updateBrandingConfig(config: BrandingConfig): Promise<void>;
    updateCartItem(productId: bigint, newQuantity: bigint): Promise<void>;
    updateDescriptionTemplate(id: bigint, name: string, content: string): Promise<void>;
    updateDiscountCode(id: string, code: string, discountType: Variant_percentage_fixedAmount, value: number, active: boolean): Promise<void>;
    updateHomepageConfig(config: HomepageConfig): Promise<void>;
    updateInventoryCount(productId: bigint, inventoryCount: bigint): Promise<void>;
    updatePaymentSettings(proOcarinaAppUrl: string, bonusItemConfig: BonusItemConfig): Promise<void>;
    updateProduct(productId: bigint, name: string | null, shape: string | null, price: bigint | null, stripeProductId: string | null, stripeProductDescription: string | null, images: Array<ExternalBlob> | null, inventoryCount: bigint | null, category: string | null): Promise<void>;
    updateProductDisplayOrder(productIds: Array<bigint>): Promise<void>;
    updateShopDetails(details: ShopDetails): Promise<void>;
    validateDiscountCode(code: string): Promise<DiscountCode | null>;
}
import type { BrandingConfig as _BrandingConfig, CartItem as _CartItem, DiscountCode as _DiscountCode, ExternalBlob as _ExternalBlob, HomepageConfig as _HomepageConfig, OcarinaFingeringMap as _OcarinaFingeringMap, OcarinaNoteDegrees as _OcarinaNoteDegrees, OcarinaProfile as _OcarinaProfile, Product as _Product, ShopDetails as _ShopDetails, SortingOrder as _SortingOrder, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCartItem(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCartItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCartItem(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateProductImage(arg0: bigint, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateProductImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateProductImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: Array<ExternalBlob>, arg6: bigint, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, await to_candid_vec_n9(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, await to_candid_vec_n9(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkoutCartItems(arg0: string, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkoutCartItems(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkoutCartItems(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearAllCarts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllCarts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllCarts();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createDescriptionTemplate(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDescriptionTemplate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDescriptionTemplate(arg0, arg1);
            return result;
        }
    }
    async createDiscountCode(arg0: string, arg1: string, arg2: Variant_percentage_fixedAmount, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDiscountCode(arg0, arg1, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDiscountCode(arg0, arg1, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createNoShippingCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createNoShippingCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNoShippingCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteDescriptionTemplate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDescriptionTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDescriptionTemplate(arg0);
            return result;
        }
    }
    async deleteDiscountCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDiscountCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDiscountCode(arg0);
            return result;
        }
    }
    async deleteOcarinaProfile(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOcarinaProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOcarinaProfile(arg0);
            return result;
        }
    }
    async deleteStripeConfig(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStripeConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStripeConfig();
            return result;
        }
    }
    async emptyCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.emptyCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emptyCart();
            return result;
        }
    }
    async getBestSellingProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestSellingProducts();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestSellingProducts();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBonusItemConfig(): Promise<BonusItemConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getBonusItemConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBonusItemConfig();
            return result;
        }
    }
    async getBrandingConfig(): Promise<BrandingConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandingConfig();
                return from_candid_BrandingConfig_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandingConfig();
            return from_candid_BrandingConfig_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCartTotal(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCartTotal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCartTotal();
            return result;
        }
    }
    async getDescriptionTemplates(): Promise<Array<DescriptionTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDescriptionTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDescriptionTemplates();
            return result;
        }
    }
    async getDiscountCodes(): Promise<Array<DiscountCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscountCodes();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscountCodes();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProducts();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProducts();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFingeringMap(arg0: bigint): Promise<OcarinaFingeringMap> {
        if (this.processError) {
            try {
                const result = await this.actor.getFingeringMap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFingeringMap(arg0);
            return result;
        }
    }
    async getHomepageConfig(): Promise<HomepageConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomepageConfig();
                return from_candid_HomepageConfig_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomepageConfig();
            return from_candid_HomepageConfig_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMostViewedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostViewedProducts();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostViewedProducts();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewestProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewestProducts();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewestProducts();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNoteAudio(arg0: bigint, arg1: bigint): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoteAudio(arg0, arg1);
                return from_candid_ExternalBlob_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoteAudio(arg0, arg1);
            return from_candid_ExternalBlob_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNoteIcon(arg0: bigint, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoteIcon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoteIcon(arg0, arg1);
            return result;
        }
    }
    async getOcarinaProfile(arg0: bigint): Promise<OcarinaProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOcarinaProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOcarinaProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOcarinaProfiles(): Promise<Array<OcarinaProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOcarinaProfiles();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOcarinaProfiles();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentSettings(): Promise<PaymentSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentSettings();
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductCount();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsBySorting(arg0: SortingOrder): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsBySorting(to_candid_SortingOrder_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsBySorting(to_candid_SortingOrder_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShopDetails(): Promise<ShopDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopDetails();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopDetails();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalInventoryValue(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalInventoryValue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalInventoryValue();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async removeAllCartItems(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAllCartItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAllCartItems();
            return result;
        }
    }
    async removeCartItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCartItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCartItem(arg0);
            return result;
        }
    }
    async replaceProductImage(arg0: bigint, arg1: bigint, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replaceProductImage(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replaceProductImage(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveNoteAudio(arg0: bigint, arg1: bigint, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNoteAudio(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNoteAudio(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveNoteIcon(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNoteIcon(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNoteIcon(arg0, arg1, arg2);
            return result;
        }
    }
    async saveOcarinaProfile(arg0: OcarinaProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOcarinaProfile(await to_candid_OcarinaProfile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOcarinaProfile(await to_candid_OcarinaProfile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async scanSheetMusic(arg0: string): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.scanSheetMusic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scanSheetMusic(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async trackProductView(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackProductView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackProductView(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBonusItemConfig(arg0: BonusItemConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBonusItemConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBonusItemConfig(arg0);
            return result;
        }
    }
    async updateBrandingConfig(arg0: BrandingConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBrandingConfig(await to_candid_BrandingConfig_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBrandingConfig(await to_candid_BrandingConfig_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCartItem(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItem(arg0, arg1);
            return result;
        }
    }
    async updateDescriptionTemplate(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDescriptionTemplate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDescriptionTemplate(arg0, arg1, arg2);
            return result;
        }
    }
    async updateDiscountCode(arg0: string, arg1: string, arg2: Variant_percentage_fixedAmount, arg3: number, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDiscountCode(arg0, arg1, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDiscountCode(arg0, arg1, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async updateHomepageConfig(arg0: HomepageConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomepageConfig(await to_candid_HomepageConfig_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomepageConfig(await to_candid_HomepageConfig_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInventoryCount(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryCount(arg0, arg1);
            return result;
        }
    }
    async updatePaymentSettings(arg0: string, arg1: BonusItemConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentSettings(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string | null, arg2: string | null, arg3: bigint | null, arg4: string | null, arg5: string | null, arg6: Array<ExternalBlob> | null, arg7: bigint | null, arg8: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_opt_n60(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n61(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n62(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n61(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_opt_n60(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n61(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n62(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n61(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updateProductDisplayOrder(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductDisplayOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductDisplayOrder(arg0);
            return result;
        }
    }
    async updateShopDetails(arg0: ShopDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShopDetails(to_candid_ShopDetails_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShopDetails(to_candid_ShopDetails_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async validateDiscountCode(arg0: string): Promise<DiscountCode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateDiscountCode(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateDiscountCode(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_BrandingConfig_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BrandingConfig): Promise<BrandingConfig> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_CartItem_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): Promise<CartItem> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountCode_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountCode): DiscountCode {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HomepageConfig_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomepageConfig): Promise<HomepageConfig> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_OcarinaProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OcarinaProfile): Promise<OcarinaProfile> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ShopDetails_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopDetails): ShopDetails {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OcarinaProfile]): Promise<OcarinaProfile | null> {
    return value.length === 0 ? null : await from_candid_OcarinaProfile_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ExternalBlob>]): Promise<Array<ExternalBlob> | null> {
    return value.length === 0 ? null : await from_candid_vec_n17(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShopDetails]): ShopDetails | null {
    return value.length === 0 ? null : from_candid_ShopDetails_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiscountCode]): DiscountCode | null {
    return value.length === 0 ? null : from_candid_DiscountCode_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    displayOrder: bigint;
    name: string;
    createdAt: _Time;
    stripeProductId: string;
    shape: string;
    viewCount: bigint;
    stripeProductDescription: string;
    category: string;
    inventoryCount: bigint;
    price: bigint;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    displayOrder: bigint;
    name: string;
    createdAt: Time;
    stripeProductId: string;
    shape: string;
    viewCount: bigint;
    stripeProductDescription: string;
    category: string;
    inventoryCount: bigint;
    price: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        displayOrder: value.displayOrder,
        name: value.name,
        createdAt: value.createdAt,
        stripeProductId: value.stripeProductId,
        shape: value.shape,
        viewCount: value.viewCount,
        stripeProductDescription: value.stripeProductDescription,
        category: value.category,
        inventoryCount: value.inventoryCount,
        price: value.price,
        images: await from_candid_vec_n17(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: [] | [string];
    primaryColor: [] | [string];
    logo: [] | [_ExternalBlob];
    siteName: string;
    favicon: [] | [_ExternalBlob];
    secondaryColor: [] | [string];
}): Promise<{
    theme?: string;
    primaryColor?: string;
    logo?: ExternalBlob;
    siteName: string;
    favicon?: ExternalBlob;
    secondaryColor?: string;
}> {
    return {
        theme: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.theme)),
        primaryColor: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.primaryColor)),
        logo: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.logo)),
        siteName: value.siteName,
        favicon: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.favicon)),
        secondaryColor: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.secondaryColor))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripeAccountId: [] | [string];
    name: string;
    email: string;
}): {
    stripeAccountId?: string;
    name: string;
    email: string;
} {
    return {
        stripeAccountId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.stripeAccountId)),
        name: value.name,
        email: value.email
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quantity: bigint;
    product: _Product;
}): Promise<{
    quantity: bigint;
    product: Product;
}> {
    return {
        quantity: value.quantity,
        product: await from_candid_Product_n15(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    active: boolean;
    value: number;
    code: string;
    createdAt: bigint;
    discountType: {
        percentage: null;
    } | {
        fixedAmount: null;
    };
}): {
    id: string;
    active: boolean;
    value: number;
    code: string;
    createdAt: bigint;
    discountType: Variant_percentage_fixedAmount;
} {
    return {
        id: value.id,
        active: value.active,
        value: value.value,
        code: value.code,
        createdAt: value.createdAt,
        discountType: from_candid_variant_n33(_uploadFile, _downloadFile, value.discountType)
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heroImage: [] | [_ExternalBlob];
    promotionalText: string;
    heroMotto: string;
}): Promise<{
    heroImage?: ExternalBlob;
    promotionalText: string;
    heroMotto: string;
}> {
    return {
        heroImage: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.heroImage)),
        promotionalText: value.promotionalText,
        heroMotto: value.heroMotto
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    scaleName: string;
    fingeringMap: _OcarinaFingeringMap;
    iconMappings: [] | [Array<string>];
    noteDegreeMappings: _OcarinaNoteDegrees;
    noteAudioBlobs: [] | [Array<_ExternalBlob>];
}): Promise<{
    id: bigint;
    scaleName: string;
    fingeringMap: OcarinaFingeringMap;
    iconMappings?: Array<string>;
    noteDegreeMappings: OcarinaNoteDegrees;
    noteAudioBlobs?: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        scaleName: value.scaleName,
        fingeringMap: value.fingeringMap,
        iconMappings: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.iconMappings)),
        noteDegreeMappings: value.noteDegreeMappings,
        noteAudioBlobs: record_opt_to_undefined(await from_candid_opt_n40(_uploadFile, _downloadFile, value.noteAudioBlobs))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    address: {
        street: string;
        country: string;
        city: string;
        zipcode: string;
    };
    openingHours: {
        tuesday: [] | [string];
        wednesday: [] | [string];
        saturday: [] | [string];
        thursday: [] | [string];
        sunday: [] | [string];
        friday: [] | [string];
        monday: [] | [string];
    };
    shopName: string;
    companyDetails: {
        taxId: string;
        vatId: string;
    };
    contactDetails: {
        email: string;
        phone: string;
    };
}): {
    address: {
        street: string;
        country: string;
        city: string;
        zipcode: string;
    };
    openingHours: {
        tuesday?: string;
        wednesday?: string;
        saturday?: string;
        thursday?: string;
        sunday?: string;
        friday?: string;
        monday?: string;
    };
    shopName: string;
    companyDetails: {
        taxId: string;
        vatId: string;
    };
    contactDetails: {
        email: string;
        phone: string;
    };
} {
    return {
        address: value.address,
        openingHours: from_candid_record_n48(_uploadFile, _downloadFile, value.openingHours),
        shopName: value.shopName,
        companyDetails: value.companyDetails,
        contactDetails: value.contactDetails
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: [] | [string];
    wednesday: [] | [string];
    saturday: [] | [string];
    thursday: [] | [string];
    sunday: [] | [string];
    friday: [] | [string];
    monday: [] | [string];
}): {
    tuesday?: string;
    wednesday?: string;
    saturday?: string;
    thursday?: string;
    sunday?: string;
    friday?: string;
    monday?: string;
} {
    return {
        tuesday: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.tuesday)),
        wednesday: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.wednesday)),
        saturday: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.saturday)),
        thursday: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.thursday)),
        sunday: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.sunday)),
        friday: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.friday)),
        monday: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.monday))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    percentage: null;
} | {
    fixedAmount: null;
}): Variant_percentage_fixedAmount {
    return "percentage" in value ? Variant_percentage_fixedAmount.percentage : "fixedAmount" in value ? Variant_percentage_fixedAmount.fixedAmount : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n51(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Promise<Array<CartItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CartItem_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiscountCode>): Array<DiscountCode> {
    return value.map((x)=>from_candid_DiscountCode_n31(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OcarinaProfile>): Promise<Array<OcarinaProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_OcarinaProfile_n37(_uploadFile, _downloadFile, x)));
}
async function to_candid_BrandingConfig_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BrandingConfig): Promise<_BrandingConfig> {
    return await to_candid_record_n57(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_HomepageConfig_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomepageConfig): Promise<_HomepageConfig> {
    return await to_candid_record_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_OcarinaProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OcarinaProfile): Promise<_OcarinaProfile> {
    return await to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_ShopDetails_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShopDetails): _ShopDetails {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_SortingOrder_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortingOrder): _SortingOrder {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob> | null): Promise<[] | [Array<_ExternalBlob>]> {
    return value === null ? candid_none() : candid_some(await to_candid_vec_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripeAccountId?: string;
    name: string;
    email: string;
}): {
    stripeAccountId: [] | [string];
    name: string;
    email: string;
} {
    return {
        stripeAccountId: value.stripeAccountId ? candid_some(value.stripeAccountId) : candid_none(),
        name: value.name,
        email: value.email
    };
}
async function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    scaleName: string;
    fingeringMap: OcarinaFingeringMap;
    iconMappings?: Array<string>;
    noteDegreeMappings: OcarinaNoteDegrees;
    noteAudioBlobs?: Array<ExternalBlob>;
}): Promise<{
    id: bigint;
    scaleName: string;
    fingeringMap: _OcarinaFingeringMap;
    iconMappings: [] | [Array<string>];
    noteDegreeMappings: _OcarinaNoteDegrees;
    noteAudioBlobs: [] | [Array<_ExternalBlob>];
}> {
    return {
        id: value.id,
        scaleName: value.scaleName,
        fingeringMap: value.fingeringMap,
        iconMappings: value.iconMappings ? candid_some(value.iconMappings) : candid_none(),
        noteDegreeMappings: value.noteDegreeMappings,
        noteAudioBlobs: value.noteAudioBlobs ? candid_some(await to_candid_vec_n9(_uploadFile, _downloadFile, value.noteAudioBlobs)) : candid_none()
    };
}
async function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme?: string;
    primaryColor?: string;
    logo?: ExternalBlob;
    siteName: string;
    favicon?: ExternalBlob;
    secondaryColor?: string;
}): Promise<{
    theme: [] | [string];
    primaryColor: [] | [string];
    logo: [] | [_ExternalBlob];
    siteName: string;
    favicon: [] | [_ExternalBlob];
    secondaryColor: [] | [string];
}> {
    return {
        theme: value.theme ? candid_some(value.theme) : candid_none(),
        primaryColor: value.primaryColor ? candid_some(value.primaryColor) : candid_none(),
        logo: value.logo ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.logo)) : candid_none(),
        siteName: value.siteName,
        favicon: value.favicon ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.favicon)) : candid_none(),
        secondaryColor: value.secondaryColor ? candid_some(value.secondaryColor) : candid_none()
    };
}
async function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heroImage?: ExternalBlob;
    promotionalText: string;
    heroMotto: string;
}): Promise<{
    heroImage: [] | [_ExternalBlob];
    promotionalText: string;
    heroMotto: string;
}> {
    return {
        heroImage: value.heroImage ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.heroImage)) : candid_none(),
        promotionalText: value.promotionalText,
        heroMotto: value.heroMotto
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    address: {
        street: string;
        country: string;
        city: string;
        zipcode: string;
    };
    openingHours: {
        tuesday?: string;
        wednesday?: string;
        saturday?: string;
        thursday?: string;
        sunday?: string;
        friday?: string;
        monday?: string;
    };
    shopName: string;
    companyDetails: {
        taxId: string;
        vatId: string;
    };
    contactDetails: {
        email: string;
        phone: string;
    };
}): {
    address: {
        street: string;
        country: string;
        city: string;
        zipcode: string;
    };
    openingHours: {
        tuesday: [] | [string];
        wednesday: [] | [string];
        saturday: [] | [string];
        thursday: [] | [string];
        sunday: [] | [string];
        friday: [] | [string];
        monday: [] | [string];
    };
    shopName: string;
    companyDetails: {
        taxId: string;
        vatId: string;
    };
    contactDetails: {
        email: string;
        phone: string;
    };
} {
    return {
        address: value.address,
        openingHours: to_candid_record_n65(_uploadFile, _downloadFile, value.openingHours),
        shopName: value.shopName,
        companyDetails: value.companyDetails,
        contactDetails: value.contactDetails
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday?: string;
    wednesday?: string;
    saturday?: string;
    thursday?: string;
    sunday?: string;
    friday?: string;
    monday?: string;
}): {
    tuesday: [] | [string];
    wednesday: [] | [string];
    saturday: [] | [string];
    thursday: [] | [string];
    sunday: [] | [string];
    friday: [] | [string];
    monday: [] | [string];
} {
    return {
        tuesday: value.tuesday ? candid_some(value.tuesday) : candid_none(),
        wednesday: value.wednesday ? candid_some(value.wednesday) : candid_none(),
        saturday: value.saturday ? candid_some(value.saturday) : candid_none(),
        thursday: value.thursday ? candid_some(value.thursday) : candid_none(),
        sunday: value.sunday ? candid_some(value.sunday) : candid_none(),
        friday: value.friday ? candid_some(value.friday) : candid_none(),
        monday: value.monday ? candid_some(value.monday) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_percentage_fixedAmount): {
    percentage: null;
} | {
    fixedAmount: null;
} {
    return value == Variant_percentage_fixedAmount.percentage ? {
        percentage: null
    } : value == Variant_percentage_fixedAmount.fixedAmount ? {
        fixedAmount: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortingOrder): {
    bestSelling: null;
} | {
    newest: null;
} | {
    mostViewed: null;
} {
    return value == SortingOrder.bestSelling ? {
        bestSelling: null
    } : value == SortingOrder.newest ? {
        newest: null
    } : value == SortingOrder.mostViewed ? {
        mostViewed: null
    } : value;
}
async function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
